language: objective-c
matrix:
  include:
    osx_image: xcode7
  - os: osx
    osx_image: xcode7.1
  - os: osx
    osx_image: xcode7.2
  - os: osx
    osx_image: xcode7.3
xcode_project: felix-catyears.xcodeproj
xcode_scheme: felix-catyears
xcode_sdk: iphonesimulator8.4
